#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。
name: 一生うるさい!!
# 描述/签名
description: 然后我又将沉默不语


#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMTEhUTExMWFRUXGBgXFxgYGBgYGBkYFxYYFhoaGB4aHiggGBolGxsYIjEhJSorLi4uGB8zODMtNygtLisBCgoKDg0OFRAQGi0dHh0tLS0tKy0tLS0tLS0tLjctNy0tLS0tLS0tNy0rLTcuMSsrLS0tNS03LS8tNi0tLS0tLf/AABEIALcBFAMBIgACEQEDEQH/xAAcAAEAAgMBAQEAAAAAAAAAAAAAAwQBAgUGBwj/xABCEAABAwIEAwUFBwIEBQUBAAABAAIRAyEEEjFBBVFhInGBkaEGE7HB8AcyQlJi0eEUIxZygvEVMzSS0kRTY4OyF//EABkBAQEBAQEBAAAAAAAAAAAAAAABAgMEBf/EACARAQEBAAIDAAMBAQAAAAAAAAABEQIhAxIxQVFhIgT/2gAMAwEAAhEDEQA/APhyIioIiKAiIgIiICIiAiIgIiICIiAi7HBfZbGYv/p8NVqD8wbDPF7oaPNd3/8AlfFcuYYdruja1Fx7rP16K5U14pF0OK8DxOGIFehUpToXtIB7jofBc9LMUREUBERAREQEREBERAREQEREBERAREVBERQEREBERAREQEREBERBkBfT/ZL2QpUPdVcXRNetULSyhBNOmHloBriLvgk5CYECeQ5v2OezzcTizVeA5mGDamUx26rnZaTSCPuzJP8AlHNfZOKlzGvearWNbmb7wicpqtAzEAdo9t0WXfw8Zb328/n5XM43HoOCYk1KTXNILAHNAAjNlOUkNiwlpAA5rhYp1Nzs9apUo1G9khklkNBBEQZvmIMAw4DdT8E4y2lgffVHsys95lFu0BUcGwRsSRFrA30XPr8Xo4hofUFWmyAQ4NBLs7e02xIFwAOpXbhws5Xrr+PLz5y8OO3v+ungOJUcUH4ZtUV2sawOL2hzHg27YcJLjvEi22i+U/ab9l5og4rBNmiZc6k2SWC7pbMkti8bbW09Z7LMY3H5PfO0DqADuzVp5nVAHWIEEEbdppFrT9D4oQ6nlGVrpGXNOUVAQWz/AKoHis+bhOPLJ8dPB5beNtfjdF637T/Z1mCxzmUg4UajRVph34Q4kOZ/peHDuA7z5JeR7hERAREQEREBERAREQEREBERAREVBERQEREBERAREQEREBERB9T+yHiLaGHxRaM1V9Sl2JgubTa9wAI0zEls8yF77j1d9cMpGqym8sFc0g0PBn7rXGL9mIgaMm+o/PnCeK1MO/Mw6xI5gGV6V/tca1XPUcWzED8IhpaPIEgdF7fBeHX4seH/AKPH5Ntncr7FxDD0a/CiWE0WUxlIcJLSyWvAymTLnWvHZG1lyeG40jiIpOqRh21nMY0ucab3e8bnAcQZIdDzMAuBjmeDhfbemyniMN2XNLREyQ4mlSpFo/7SfErw1bihysE9phNzIdM5pPeSetl34ceuUt+uVluZPj6NxBpq1sQxlEZ21302ECDTLarQLuIgPaRLTYgzzXpvYn2ne/8As1zme1xaQS2YbkJcdCO0dIiG818y4p7RN/tPLw73lPNU3Je8XzHXM0yAeRjv5WK9rGtLnU2xUOp1kmcxnmZNu5a53heOcqxPH5PbeMd77ceIMq1cOGxmY2oDeey4sLfXP5r5ep8Zi3VHFzzJ+XJQL5nksvL/AD8fT8fG8eMlERFhsREQEREBERAREQEREBERAREVBERQEREBERAREQEREBERAREQZBQuKwiu0ZlYRFAREQEREBERAREQEREBERAREQEREBERUERFAREQEREBERAREQEWYWEBFmEhBhEWWtJsBPcgwi2cwixBHfZYhBhEWzmEagjvQaoiICJCICIiAiIgIsgKQYZ8gZHSdBlMnuQRIu1Q9kse/wC7gsSf/pqR55YXXwf2YcVqCf6RzB/8jmU9OjnA+iLjxyL1WK+zrijHZTg6h6sLXt82EhFNMrTCewuKeJdkpnZr3HMfBjXeq6/D/svrPBL69Ng6U6z9p1yADzXuqfExNizwLfqFcpcZfl7IBA1gH9uSXk1keId9lAAvjDmtA9wQNeZqDaNt1cZ9ktAsti6xdGow7S3bb3kwvSf8UkybDQ3ifSyuYfi1ImAQSbS58xfS4WPemR5XAfZDhzHvcXW6htFrSe6XH4Lqn7F8AbtxOJaN8zac+Fgu7T4mx35TygHb/LqrzceSNHEAW2HhcJ71K8dW+xvBhvZxGInupui03AHzWlP7E8O8dnHPadZcxkej17dnGGNgOzQDp7ymB5ZlvV9ocKJLmFxsf+a0nwjUq+ybHg2/YZTBh2PdOwFDnofvqwz7E8GIz4+qeeWm0dOZheoHtRhTpTtyLzpM3EqT/EjA61Fskfmz91jZPYcKn9h/Dj/6vEHuNL/wsuhhPsf4RTlrzWqHm+pHlkDQrruKvm2GDQRO3IHwWtfiDjd1MRyJIkc5BlT3MUeI+wfA6cAYYujUtxFa/fL/AIQuVX9k+EkEMwAab39/iXQdol8LoO4kJvTaIP53A+sgIceTpRb3hzpv0sCp70xwWewfDxGag/kZruE9bLqYDgWApR7rAUzvmeDWMxGtUmNJsApxXqDXDAEgXJcDz5RCe+qmQKbRexzaa/pPxU9qrotqUoH9mjzgU6cb7BsLo8Oxs5sjKVMwbkZdxysCuG3D4o6ZLmBLnf8AgtmOxmhFMxbLckg84b85uptN16x1Nhh9StSJjTK1xvGk/sq2N4RhK0CpQpVoiHupMIBvH3WzN9wvOUaVe4/tyZNs+2pbeJ81PSwVYXgtJg2z3E627lfZO/27dRjKTQGUaLQ2NGQB4AWJHlKjPHDYEC4uDDhednDa3PRcuvhcQNPeVAd2++gk941Hiq76FeezQeZg5nMqyBG0HW+42T2pjst4lTbYUqZj9DIFtAANVtVZRqtyvwuHe0xZ9JhBkm+n1IXDouxTTABYDYE0nAcpObZbnG8QmGwR+l2a4nYwIjZPari8/wBnOG5b4DDEgWim0dbkQTZQD2W4RId/QUieUOjlcZo66LnvxOPBM0XAa2Dmi/TRZZisWR2mwN494becJ7cjHSpcI4c0HJgsM3vpMcdZ1cDZdXB12gH3baYaBoGBrQLSezaNT4LjniNNoHvKFcugXILRAGo7M/WpWanFqDsvuxVaRGaX21ncT4iNVnb+ars4mnSqt7bKTwRMuptIIJvZzZdbYBYw1KjTtToULSJbRY0ADraJ5LzbeMtkZm1KhnXM8iPn5bLoO4jQfqw7iBnA6WeY56Qp7f0d2lxeeyxlNxiIYO/Symdj3vB7LRFzOo2t42XJY/DjXMzpTcOe8k8tlLVFN/aNbENAvBYBaZMFoA80tt/JFt2HY65eJ1s5wi0wQAov6NxPZgi8Q4Xv+oarg4io+QGF/iR93a8m/wC6lpUCb1KmTaJLibfW4WJWquYvhb83Zc3S99+kDRFrXwlGf+a4W+u5YXSDxFH2eqHR9t4k2Pc1b0+B09DWOl4k+UCyU/aRzCQ2W7WdJt3WWz/aBz3WaHHS7Wwb7kX+K67WekTPZ+hqS8jWxj4wrf8AhzCAHK177Td4gAG5t81WqcSfMZLfpzG+k23U44lWcNwRaMzpgQQCAdJ5hZ2qwMJhWgn3JMadsm47j8VHTdhif+nHL8XrBlWBVqPOZ7wDYZruiI08ossF35qgdysTN4jWQIlRGr6mFY7KcK09SXfCVOziWHbMYOiJ/Tfrus0sIyCS+nOwBdJjTQEDzWpLD95lucuj+FBh2Po7YNpdzFMC+8JT9pQwHLSLeUOYBsL2nyUz3YcgMLDyMue/0dp4KGlRpEdmiwgfpbN/GT5ojV/tY6bgAdTm6bLSv7TAnaNgR06HmpBRp3y0aIMa5QIgbS71VMUqUnM0QAQIaDBMX7MadUHSPG2lshzLnZrifUQfNSM4vIAzMmbjLBv5yubTq4a4dWbTHL3EzHcLKhiMZTBmlVBG39oAAeO6YmvW4PjwpiC2DrMHMRsPuwAp8XxWk4AZXm1wIiBPauBHKOi+d1+Jl2jp/wBIA9Ebi7S5o0jMBfxk2VmxHuP+KYU/fFTnAcLHqTEeEqIcRw5hrc1Pmc4jXkW/BeIOLgRppyWHV5vHcpg+jjH4Cg0B2Ss43zf3Hm/OYA8Ft/iPBASKDP05jfffMbBfNjWgaQe828lGKo5T528iLyqmPpD/AGowxg+5c1sjTNGnR1tlmn7ZYYOMUXwObiSdIi6+cUaoBuM3eHD5graq5syCQNgGk2/1EqZf2uPpVL20Z+HMw8pIjrfdW6ftCT2hUcLTepTA9fgvkwxZ0zuI5fwpKuKtEeMRFvAJlH1qr7TNc2BLiegJ8NfgqGM9pGtABZUba+Y9rl0C+cMBDZL2a6SMw12mQtX1HG4JPidPPVO1e6q8fpuGumkuAtuNPq6pVOP0LSzMBtLTr6ryRa4zJJNoi/gpGYSrfskj/LA9VMV6N/tDQM5aIaZ5BwPwUv8AiamQBFIbfcIPxXmv6V0DNaBES76Cs0MLSmCSf8gPTms5Fd3/AIrR/G4R0DZPf2hCq1cfhSLtrN1gh7CNT+FxHxUtCnw/L2vfzvZuWJjfUrm4tuFB/tGRqM1MT4kJZCVhnEmh0MDnN6gA+jiunS4tUHabRI6+8+o2XEDmEW12AY1o9FVxbYjWI5fukkpXrantXiW2EjpnHzCLxD8Qy2unRFvDVqm5jbCb2MkH/ZXGVnOHZdBGuWZjqQNFwiCAJBuOslZ945pIvrub+K72I7NOuP8A3HeH8+CtYWnhtXvfN7aDVebbUfeCfBSMwtR5AbTe4nYAuM+C5+o9xSx3Cw2HU6sx973jvhpqq2J4zgNKdKqORzX9dLLzzfZvFmYw9YExIyVNhAtFrRpzWlfhdRnZeHB1gQQWxsQQRqriduniuKUfw+9HeR+yjpY+0tc9sHkXR37fuuc5nNoHK5PxPRb022jLHMyf3iVLBeqYuoJh7pMWLYnWe75rl4jFE6uJPgsmm7YGO4qdnDZbmJEmwAImeo5IKVSpGsjvnT6lZ/qG/md1jSPAqT+mEkQfPcq3h+EVHglrB4uDR3ySE6FD3pdAzSOZAHK0m8KF5POR8bjTmuhXwL2yAWuaOTwBPKDfRVwwxcxHX0TRE6qS3KGtEXnJ2u4lRtmevQdystfoc3oZXY4fxOoJyGmSdc1Jj4vtmBUtRxIECCZ3MR5WPxWovMvdNoGWZ7zIi3Rd3E0q75JNLnbK30Aj/YqH+jJaRFN0kRds6i57MnlYhTWpHJE/Q/lbOJcSQGDoLA32uV2KfDaZjPlZzghxnW0xAVPEYJrT2anQ2Gvi481NMVXUnfljeb6fsstc63LxQ1XNJEmZ6fJaHEu2+frKdjo0MJUcbOF9dvAq6aBB7dUHaxJ0i1xK84+tUG7vCfNS0Kz3ntPieZg87zZTKPU4V1ECDBGhMNnW+o9ZV2kMOZy0223cQf4Xjab6nPNfTMI33BQ4qppAt1HqZ1Uyj3JNHXIJtEBotbSfrVdPhT8E0TVpuN/zEt8Wg3gBfOKVR7gIB74d8VYp0qka26u17k7Pr6q2vwrWKcxvTJ87LRo4UbAUL/oI8jltC+VPqEWtbqUGLe0zG+v10V2pj6I+jgN30wREwXQQO4TNwNlFiMFgXWzOEibhxPKBIvzkrwJxpB03uQQ7zU9DGkjsyTc2F+g5eAWbrT0VXhWFBEPqEby0Dlod/RRVOE0M0h5a2DPZBjuBOq49HitRoh22xJB8JMSpmcXM3BAIv2ZHOw32SaqHF4GnIjMRA2H/AJLKhxGNpE6bdB6Itdo802poAPS/pqpPfkaggzv+x1UAEXk25KUnMDJzOPMuJ+N16qylbjZIkeVt1eocWDRP9wHYteBed7LmAHTNY+ikfQEfemfAeCxZB1X8fquEGo8j9VR1+e8FQDih1Nz5jxMqi3DtBs7yMHRTUqIJF9dSTN/BZyCycdmIkAE76LVtfMYmJ8PMrZ2CJIuHGLxAje/MrdlFsCGEne9j4AW19U6Gv9Q4AgOI2gGx8tVuwCLzqe4eszKuV+GuyNcBTk2DWh2cnQzaJ313XOcxw1bbmeYKlotUw3VzjH6cs28ZHkt39rTO6NiCf/yqba0ODgWh0zeOc72XWZ7UYgGc7STp2W67RHyWUc7Gl0iWusAIdIty1sq7SY287Lo4r2qxLwQ6q487N7uS5VhYDN4n5wqJTUiR2DNvug7RY7eCyaxaRDBMfihwKrS7lB0vNvJaYnDPadGkRqCcp7iQJUIsuxb5kQ3/ACtI9ApH4itULiXPc4CSXGdDtIsuTnO5AW7MSJ7U+F/iriulSqVDZwJ7ztZaPwrnkwA3pPfzVN1a1ifIRN/lC0fVfEzbS6mD0A9l8VlBLCAd8zIM3H4vkufWwdSmSxwG1iAduYPzXPGJcL+lo8ll2MBG4O97J2LDqUG5jz8ytCfrdRF5deSdjy80cMsdsEmRAmRHORB8CirdJzescyf2KzVxLNhHTb1uqUiNyTuTA8la4fg3VXZWxO8ua0DxcYQTsx1sud8cvw6nST3LAxEGQ4+B5fNWKvBao7INJ3dUYT430VVmFLSfe9kDkQZJjTpF5WehLi8WXdoPcRYDMZ+hPxVcV/oWU1bF5AMvuovbJLvEkEHfdVBi3SYJBP5QB6BWCw1r3XDSQNTBIHeRYLFPMbCPMD4q7g34pzREZDaXhoHMzmVrCtpyRX92BuWE5jHLLbxUtVyXB3Jw1vFttCLFbf1J+6W9Sd+l+Uq3jW0wctNxLRMTqJ676Bc2tUkXzE8yZCs7RBWqOJ0GnRFDVcJ/3RaRMA0fek90StalWdj0utq1Vp+85zjGuvxUIfJF9PRdqNgNDlKy2sIgiTHLRRgg6a/G6AjmZ9Ijosoka4cr9VZZWkaARuBp4qm8iTEkDc29Fu54I1jnG/goL39WyIgzzE6b2Ov8rU4vk4jwVegxt5IB2Bk/AfFbRodvAeSmRWHVpvJT31o38QpKwblsHTY3c2PICYVc5v0x0F0E9NwIMvywCQIJk8ha08ytXFux+p9FrQpEm7g3qdPSVtUzgZS9pHQgx3KUS0w/KXAOyz3idplYbixBER1GvdAsqzSd9PBZfUuAQB4CfMXKmDNeo0AAC+5mR4CBC1dibQBPUyTPS8DRbVarYgAb3AMnvBMBaGq0giItaI9VUSVH0yBFID/U8z0uT8tFo2BMgGRzcADt5KETzA8Y+SU2fqHiorZ9K0i46A7/AAWWYcnbrcjQDqVYq0jDe2wyJsZiJF+SixABjWQLyZnutayCB19FqBoPruUnuSea2OGMSZtrrbvQYa5zSBBbF+Z5gqWphahp+8yH3YOpsJ5xN/BQvpi5zHaN+/QKOm/mZjmTH8KKlqQACLaSJvMbXlVn1e9SSPxT4ct0IB0v4ftqqjalXe3mPPQqatXcdTr3+eqhziNADOt59VOcO+A/Z0w4kC9idVFaNdexj4qzBIJlx/bdVqjnkjM42FpdNuQSnWy7k+P7hBORuD8z4oxzp28ZJWj6jnfQC2ZXy/zCYLHvnggiWkdIvvqquOcDBJv+I3uST15K2/FyACRp0Cy3BU3ETUY2187yB4ENMJBxKxM2O3JYVnGU2B0A+oPrCwt7EaBxJW2UnWVYwuEJYXF1NsbF3aPcBqtC2YiO+37LrURxGl+8X+K3YL3FvGI8CjR0upWs6fUrOqOZTi2cnqAG/EqUUWBpMwRoNZ/aP2W+Gw9OZeKkfpgepkKTE0qIuxzjP5m/sb+SwNW4w+7DMzokkNns98Rr4pUBLZMjedz6rfAgZgC0PE/dJgE6cwreJ4e5klwa3oDOt7QSPVS2DnVJtdxsPvGdtugWlRxNycx27tdCOa7mHw1ItzPbWDR+JjbHpJBAKo480c00TUIj8cFw8RspooA2Gaf91N2TFyBvAHXrCB5BB0PPc76+K1e6TJ11k3nmgje4jnB5x4bLDQeXjzUj6XTTUhSe8BIAgaa/uVBpTfSDHDI/OdCHgN8REnzVct/RYjVdzE4FgYC2q1x/K51/TX0VGrTESO60kTA/nyTRSqkOiWjQDsgA2lHUQBbeJ56SNlcdWsWuaDykGxsZEEXPVVyOQcL78/krowcGRBymLwb3j5rRrRe9o5fG63On3b78zvdYp0x39NPmoN8xiBb4986+C0d71p1gg2vB6LGIbEG95n8uvPdRTtpPloipX1SXzVc5xJ7R1PrutWObcGmHTvGVw7ioHv0mfJHuANiT6JgyKI2nuH1dSUuw4GHCDrvb5qJtUg8/C3PQhZNYnXQ9P4QWHvZJ7LhNzmyixk6RErBr5HdiW6GHAd9+irOrfeFjMTYT0gkW8FqzLebcu/5JiLRx7zIc919gBGs76DuWcLXAs4gdYnbS31dQtpToDJvryWrakH6KK69ClmYXZ2iBOUubJ7hqVSq45zvvHMBaTew2VV1YT2Rl9Qb79FM2uMsFodsHNIBbeTaL8rpgldVEAGCJ2N1BUew6OcD4EfHuUXuRqXER3HXTlKqVTl3K1IjauL7acj8llUn4pwtP15rC1lHXZSBP3u5WRSa2ziZ8ERbL8Xme7DYBuf09r/u2Slhi64Eg9w0BPwCIsUnbau52UML3wD90nsjyUrMPRyT7w5/y+78fvZvksos2ivTeM0D69FJWxDQAG6ixtER13RFFV34okXaAPP5qZzwBBbkBEzqXTsYJtZYRaxIhbAvYidwZsrdHh7qk5WdR2hYa+NgiLFVPhuBFwM1Ws5g59/8AKCqWL4b7t0FwMibTpsiKSmKr2Bo3/lY94dJcBrry3RFpGrHxrpPj5qJ2KM7D/ZEVkG7axIu63j6IXg8tOslESxWHPtBF4+Sjz/NEUg3pvZBBbJOhk2vy3UbmjYn6+giJgyWk6yepP8qRtLMILojQR/KIpfgquojvWG0PLvvKIm0WWM1GY6joN56rQ0hMu+fd0REl7GtZggQ503mYjpEGVq+kQAZF+U275HwWUVtENXDuaASZHT+e9UqlQjdEWuKK1bESdERFtH//2Q==

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://media3.giphy.com/media/W9qCmeTuUoaFG/200w.webp?cid=ecf05e472m62wzagdz1mqg72xuuygnk8efqz6kfevgdg5h37&rid=200w.webp

# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
  - name: 更多
    url: /more



# 每页的文章数
paginate: 15

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo: claradoesntcare #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: conundrum1804@gmail.com
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: #FromEndWorld/loffer #https://github.com/<>
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: 有一个绿鸟在讲话©2022


# 评论，注意，请不要同时添加多种不同的评论区

# 输入Disqus shortname，即可添加评论区

# 输入Gitalk相关设定，即可添加评论区
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

# 输入Google Analytics web tracking code
google_analytics:

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: 

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /schwarzeis


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

excerpt_separator: "<!-- more -->"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

